import { HealthRecord, Product, ForumPost, Vet } from './types';

export const MOCK_HEALTH_RECORDS: HealthRecord[] = [
  {
    id: '1',
    petName: 'Buddy',
    date: '2025-07-26',
    type: 'Vaccination',
    title: 'Rabies Booster',
    description: 'Annual rabies vaccination booster shot administered by Dr. Smith',
    status: 'Completed',
  },
  {
    id: '2',
    petName: 'Buddy',
    date: '2025-08-08',
    type: 'Vaccination',
    title: 'DHPP Core Vaccine',
    description: 'Distemper, Hepatitis, Parainfluenza, Parvovirus combination vaccine',
    status: 'Scheduled',
  },
  {
    id: '3',
    petName: 'Luna',
    date: '2025-06-12',
    type: 'Lab Report',
    title: 'Complete Blood Panel',
    description: 'Routine annual blood work — all markers within normal range',
    status: 'Completed',
  },
  {
    id: '4',
    petName: 'Buddy',
    date: '2025-05-20',
    type: 'Prescription',
    title: 'Apoquel 16mg',
    description: 'For seasonal allergy management — 1 tablet daily for 14 days',
    status: 'Completed',
  },
  {
    id: '5',
    petName: 'Luna',
    date: '2025-09-15',
    type: 'Checkup',
    title: 'Annual Wellness Exam',
    description: 'Comprehensive physical exam including dental check, weight, and vitals',
    status: 'Scheduled',
  },
  {
    id: '6',
    petName: 'Buddy',
    date: '2025-04-10',
    type: 'Checkup',
    title: 'Post-Surgery Follow-up',
    description: 'Incision site healing well, sutures removed, cleared for normal activity',
    status: 'Completed',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Premium Organic Kibble',
    price: 45.99,
    category: 'Food',
    image: '/images/product-food.png',
    rating: 4.8,
    reviewCount: 342,
    description: 'Grain-free, human-grade ingredients with real chicken and sweet potato. Veterinarian recommended.',
    stock: 156,
    badge: 'Best Seller',
  },
  {
    id: '2',
    name: 'Orthopedic Memory Foam Bed',
    price: 89.00,
    originalPrice: 119.00,
    category: 'Accessories',
    image: '/images/product-bed.png',
    rating: 4.9,
    reviewCount: 518,
    description: 'Medical-grade memory foam with washable cover. Perfect for senior dogs and pets with joint issues.',
    stock: 43,
    badge: 'Sale',
  },
  {
    id: '3',
    name: 'Interactive Puzzle Feeder',
    price: 24.50,
    category: 'Accessories',
    image: '/images/product-toy.png',
    rating: 4.6,
    reviewCount: 189,
    description: 'Stimulate your pet\'s mind with 3 difficulty levels. Slows eating and reduces boredom.',
    stock: 210,
    badge: 'New',
  },
  {
    id: '4',
    name: 'Organic Training Treats',
    price: 12.99,
    category: 'Food',
    image: '/images/product-treats.png',
    rating: 4.7,
    reviewCount: 267,
    description: 'All-natural, single-ingredient treats. Low calorie, perfect for training sessions.',
    stock: 380,
  },
  {
    id: '5',
    name: 'LED Smart Safety Leash',
    price: 34.99,
    category: 'Accessories',
    image: '/images/product-leash.png',
    rating: 4.5,
    reviewCount: 134,
    description: 'Reflective LED leash with 3 light modes for nighttime walks. USB rechargeable, waterproof.',
    stock: 88,
    badge: 'New',
  },
  {
    id: '6',
    name: 'Joint & Hip Supplements',
    price: 29.99,
    category: 'Health',
    image: '/images/product-supplements.png',
    rating: 4.8,
    reviewCount: 421,
    description: 'Glucosamine, chondroitin & MSM formula. Vet-approved for mobility support in all breeds.',
    stock: 195,
    badge: 'Best Seller',
  },
  {
    id: '7',
    name: 'Professional Grooming Kit',
    price: 54.99,
    originalPrice: 74.99,
    category: 'Grooming',
    image: '/images/product-grooming.png',
    rating: 4.7,
    reviewCount: 203,
    description: '12-piece kit: slicker brush, dematting comb, nail clippers, ear cleaner & more. Salon quality.',
    stock: 67,
    badge: 'Sale',
  },
  {
    id: '8',
    name: 'Calming Dental Chews',
    price: 18.99,
    category: 'Health',
    image: '/images/product-treats.png',
    rating: 4.4,
    reviewCount: 156,
    description: 'Chamomile-infused dental chews that clean teeth while reducing anxiety. Grain-free formula.',
    stock: 245,
  },
];

export const MOCK_FORUM_POSTS: ForumPost[] = [
  {
    id: '1',
    author: 'Sarah Johnson',
    avatar: '/images/avatar-1.png',
    title: 'Best food for sensitive stomachs?',
    content: 'My golden retriever has been having digestive issues for the past month. We\'ve tried switching brands twice but nothing seems to help. Has anyone dealt with this? Our vet suggested a limited-ingredient diet but I\'d love to hear personal experiences before committing to a specific brand.',
    likes: 24,
    comments: 12,
    tags: ['Nutrition', 'Golden Retriever', 'Digestion'],
    date: '2 hours ago',
  },
  {
    id: '2',
    author: 'Mike Davidson',
    avatar: '/images/avatar-2.png',
    title: 'Crate training tips for new puppies',
    content: 'Just brought home a 10-week old chocolate lab. He cries every time we put him in the crate at night. We\'ve tried putting a blanket over it and leaving a toy inside, but nothing works. Any experienced puppy parents have advice? How long does it usually take for them to adjust?',
    likes: 45,
    comments: 30,
    tags: ['Training', 'Puppy', 'Labrador'],
    date: '5 hours ago',
  },
  {
    id: '3',
    author: 'Dr. Emily Chen',
    avatar: '/images/avatar-1.png',
    title: '🩺 Summer heat safety — a vet\'s perspective',
    content: 'With summer approaching, I wanted to share some critical heat safety tips. Never leave your pet in a parked car, even with windows cracked. Walk dogs in early morning or evening, and always carry water. Signs of heatstroke include excessive panting, drooling, and lethargy. Seek immediate vet care if you notice these symptoms.',
    likes: 128,
    comments: 47,
    tags: ['Health', 'Summer', 'Vet Advice'],
    date: '1 day ago',
  },
  {
    id: '4',
    author: 'Alex Rivera',
    avatar: '/images/avatar-2.png',
    title: 'Indoor enrichment ideas for rainy days',
    content: 'We\'ve been stuck inside due to rain for three days and my border collie is going stir-crazy! What are your favorite indoor activities? We\'ve done puzzle feeders, hide and seek with treats, and taught a new trick, but I\'m running out of ideas. He has so much energy!',
    likes: 67,
    comments: 22,
    tags: ['Enrichment', 'Indoor Activities', 'Border Collie'],
    date: '2 days ago',
  },
];

export const MOCK_VETS: Vet[] = [
  {
    id: '1',
    name: 'Happy Paws Veterinary Clinic',
    specialty: 'General Practice & Wellness',
    distance: '1.2 miles',
    rating: 4.9,
    reviewCount: 312,
    verified: true,
    image: '/images/vet-clinic-1.png',
    phone: '(555) 234-5678',
    hours: 'Mon–Sat: 8AM–7PM',
    services: ['Wellness Exams', 'Vaccinations', 'Dental Care', 'Surgery', 'Lab Work'],
  },
  {
    id: '2',
    name: 'City Pet Emergency Hospital',
    specialty: 'Emergency & Critical Care',
    distance: '2.5 miles',
    rating: 4.7,
    reviewCount: 198,
    verified: true,
    image: '/images/vet-clinic-2.png',
    phone: '(555) 876-5432',
    hours: 'Open 24/7',
    services: ['Emergency Care', 'Surgery', 'ICU', 'Radiology', 'Blood Transfusion'],
  },
  {
    id: '3',
    name: 'Gentle Touch Animal Hospital',
    specialty: 'Dermatology & Allergy',
    distance: '3.8 miles',
    rating: 4.8,
    reviewCount: 145,
    verified: true,
    image: '/images/vet-clinic-1.png',
    phone: '(555) 345-6789',
    hours: 'Mon–Fri: 9AM–6PM',
    services: ['Skin Testing', 'Allergy Treatment', 'Immunotherapy', 'Ear Care', 'Hot Spot Treatment'],
  },
  {
    id: '4',
    name: 'PawStar Wellness Center',
    specialty: 'Holistic & Rehabilitation',
    distance: '4.1 miles',
    rating: 4.6,
    reviewCount: 89,
    verified: false,
    image: '/images/vet-clinic-2.png',
    phone: '(555) 456-7890',
    hours: 'Tue–Sat: 10AM–5PM',
    services: ['Acupuncture', 'Hydrotherapy', 'Physical Therapy', 'Nutrition Counseling', 'Massage'],
  },
];

export const FORUM_TOPICS = [
  'Nutrition', 'Training', 'Health', 'Puppies', 'Behavior',
  'Grooming', 'Senior Pets', 'Adoption', 'Enrichment', 'Vet Advice',
];
